### ISSUE TITLE
auras default position

### ISSUE THREAD

**Issue by hubgogo** [s0h2x/pw_unitframes#1]
The default icon position should be in the red box below

v1.2.17c is at the top by default

See below：

![2023-01-19_101925](https://user-images.githubusercontent.com/91697479/213341088-ecdc0281-9979-4a2f-8193-27554a57bce7.png)

Author Can you tell me how to adjust it?

thanks

**Comment by hubgogo** [comment]
Sorry, sorry. I have found the command /mover

![2023-01-19_110644](https://user-images.githubusercontent.com/91697479/213346276-829fb845-9fc1-4c34-98df-6414bc2f44e2.png)

I also have a small problem with changing the class portraits back to the default

![2023-01-19_111058](https://user-images.githubusercontent.com/91697479/213346704-d02697b2-35b9-4ce0-a831-7f1184c7b694.png)

It looks like the picture below, it's great

**Comment by s0h2x** [comment]
> Sorry, sorry. I have found the command /mover
> 
> ![2023-01-19_110644](https://user-images.githubusercontent.com/91697479/213346276-829fb845-9fc1-4c34-98df-6414bc2f44e2.png)
> 
> I also have a small problem with changing the class portraits back to the default
> 
> ![2023-01-19_111058](https://user-images.githubusercontent.com/91697479/213346704-d02697b2-35b9-4ce0-a831-7f1184c7b694.png)
> 
> It looks like the picture below, it's great

open config (core/config.lua) and change this parameter:
config > global > classportraits = false
